services:
    postgres:
        image: postgres:17
        volumes:
          - pgsql_data:/var/lib/postgresql/data

        environment:
            POSTGRES_DB : ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
volumes:
    pgsql_data:
